// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2OUlmWehV96w1Rx_Z-dXexd_4bB_UZ5c',
    appId: '1:364620905994:web:68aa8fc5bf2297762429f3',
    messagingSenderId: '364620905994',
    projectId: 'fir-learning-b3b4a',
    authDomain: 'fir-learning-b3b4a.firebaseapp.com',
    storageBucket: 'fir-learning-b3b4a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsgKXc90GZjCKsiOcDNMmFUHGer5Ayam0',
    appId: '1:364620905994:android:db5e9f74a77b576d2429f3',
    messagingSenderId: '364620905994',
    projectId: 'fir-learning-b3b4a',
    storageBucket: 'fir-learning-b3b4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbcyDsU5Ud1a9ywKK41z5QC4N0Lv8u1Fs',
    appId: '1:364620905994:ios:53a208297a1b964e2429f3',
    messagingSenderId: '364620905994',
    projectId: 'fir-learning-b3b4a',
    storageBucket: 'fir-learning-b3b4a.firebasestorage.app',
    iosBundleId: 'com.shibamfirebase.firebaseComplete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbcyDsU5Ud1a9ywKK41z5QC4N0Lv8u1Fs',
    appId: '1:364620905994:ios:53a208297a1b964e2429f3',
    messagingSenderId: '364620905994',
    projectId: 'fir-learning-b3b4a',
    storageBucket: 'fir-learning-b3b4a.firebasestorage.app',
    iosBundleId: 'com.shibamfirebase.firebaseComplete',
  );
}
